version: "3"
# Todo pin docker versions
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
    volumes:
      - "./volumes/unbound:/opt/unbound/etc/unbound/"
      - "./a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro"
    restart: unless-stopped
    networks:
      vpn-network:
        ipv4_address: 192.168.254.13

  pihole:
    depends_on:
      - unbound
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "Etc/GMT"
      WEBPASSWORD: "80EvrFWrbJv86SdyrRSd5Ur9XrkYlEXHRAgh5D0Vay6Z7WavitPs2ufZxgsUbork"
      DNS1: 192.168.254.13#5353
      DNS2: null
      DNSSEC: "true"
      VIRTUAL_HOST: pi.hole
    volumes:
      - "./pihole/etc/:/etc/pihole/"
      - "./pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/"
    dns: 127.0.0.1
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      vpn-network:
        ipv4_address: 192.168.254.11

  openvpn:
    depends_on:
      - pihole
    cap_add:
      - NET_ADMIN
    container_name: openvpn
    image: kylemanna/openvpn
    environment:
      OVPN_DISABLE_PUSH_BLOCK_DNS: 1 # TEMP FIX FOR ANDROID
    ports:
      - "1194:1194/udp"
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
    restart: always
    networks:
      vpn-network:
        ipv4_address: 192.168.254.12

networks:
  vpn-network:
    external: true
